# Generated by Django 6.1 on 2026-08-27 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('nombre', models.TextField()),
                ('descripcion', models.TextField()),
                ('url', models.TextField(db_column='URL')),
            ],
            options={
                'db_table': 'proyecto',
                'managed': True,
            },
        ),
    ]
